import Head from "next/head";
import axios from "axios";
import Link from "next/link";

interface IData {
  data: { title: string; link: string }[];
}

export default function Home({ data }: IData) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data.map((item, i) => (
          <div key={i}>
            <Link href={item.link} target="_blank">
              {item.title}
            </Link>
          </div>
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await axios.get(
    "http://localhost:3000/api/crawling/saramin"
  );

  return { props: { data } };
}
