import Head from "next/head";
import { Inter } from "next/font/google";
import axios from "axios";

interface IData {
  data: { titles: string[]; href: string[] };
}

export default function Home({ data: { titles, href } }: IData) {
  console.log(href);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {titles.map((item, i) => (
          <div key={i}>{item}</div>
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await axios.get(
    "http://localhost:3000/api/crawling/saramin"
  );

  return { props: { data } };
}
